# frozen_string_literal: true

require_relative 'models/book_delete_schema'
require_relative 'models/book_form_schema'
require_relative 'models/book_genre_type'
require_relative 'models/book_list'
require_relative 'models/book'
require_relative 'models/dry_result_forme_wrapper'
require_relative 'models/give_book_list'
require_relative 'models/give_book_schema'
require_relative 'models/input_validators'
require_relative 'models/reader_form_schema'
require_relative 'models/reader_list'
require_relative 'models/reader'
require_relative 'models/schema_types'
require_relative 'models/store'
